package com.example.Client.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA Entity representing a Client in the system.
 *
 * <p>This class defines the data structure for a client, including its
 * unique identifier, name, and age. It is mapped to a database table
 * via JPA/Hibernate.</p>
 *
 * <p>Lombok Annotations used:</p>
 * <ul>
 *   <li>@Data: Automatically generates getters, setters, toString, equals, and hashCode</li>
 *   <li>@AllArgsConstructor: Generates a constructor with all parameters</li>
 *   <li>@NoArgsConstructor: Generates a no-args constructor (required by JPA)</li>
 * </ul>
 *
 * @author AITALI YASSIR
 * @version 1.0.0
 * @since 2025-12-09
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Client {

    /**
     * Unique identifier for the client.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue
    private Long id;

    /**
     * Full name of the client.
     * Required field for identifying the client.
     */
    private String name;

    /**
     * Age of the client in years.
     * Stored as Float to allow decimal values if necessary.
     */
    private Float age;
}
