package com.example.Voiture.entities;

import com.example.Voiture.models.Client;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Transient;
import jakarta.persistence.ManyToOne;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA Entity representing a Car (Voiture) in the system.
 *
 * <p>This class defines the data structure for a car, including its
 * technical characteristics and its relationship with a client. It is
 * mapped to a database table via JPA/Hibernate.</p>
 *
 * <p>Relationships:</p>
 * <ul>
 *   <li>Many-to-One with Client (each car belongs to one client)</li>
 *   <li>The client field is marked @Transient because it is not persisted
 *       directly in the car database (retrieved via the Client service)</li>
 * </ul>
 *
 * @author AITALI YASSIR
 * @version 1.0.0
 * @since 2025-12-09
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Voiture {

    /**
     * Unique identifier for the car.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue
    private Long id;

    /**
     * Brand of the car (e.g., Toyota, Renault, Peugeot).
     * Required field to identify the manufacturer.
     */
    private String brand;

    /**
     * Registration number of the car.
     * Unique identifier at the national level (e.g., A 25 333).
     */
    private String registrationNumber;

    /**
     * Model of the car (e.g., Corolla, Megane, 301).
     * Specifies the specific version of the brand.
     */
    private String model;

    /**
     * Identifier of the client who owns the car.
     * Foreign key to the Client entity (in the Client service).
     */
    private Long clientId;

    /**
     * Reference to the owner client.
     * Not persisted in the database (@Transient) as it is retrieved via Feign.
     * Annotation @ManyToOne indicates the JPA relationship.
     */
    @Transient
    @ManyToOne
    private Client client;
}
